### ISSUE TITLE
Ascii/utf issues with tap-jaffle-shop 

### ISSUE THREAD

**Issue by jfo8001** [MeltanoLabs/tap-jaffle-shop#10]
With this meltano configuration

```
Python 3.11.2
meltano 2.20.0
```
meltano.yml
```
version: 1
default_environment: dev
project_id: d68b714c-b309-488f-bea9-76c8b10ab909
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-jaffle-shop
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-jaffle-shop.git
    config:
      years: 2
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
```

When I run 
```
meltano config tap-jaffle-shop test          
```
I get
```
2023-10-10T20:54:46.531312Z [info     ] The default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

'ascii' codec can't decode byte 0xe2 in position 60: ordinal not in range(128)
```

I have traced this back to this line of code that expects ascii in the STDOUT stream
https://github.com/meltano/meltano/blob/2468455a3bc9d653206f46b52b02cd6e5c83131f/src/meltano/core/plugin_test_service.py#L83

Also when I run 
```
meltano run tap-jaffle-shop 
```

I am getting 
```
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

block violates set requirements: Found no end in block set!

```
https://github.com/meltano/meltano/blob/2468455a3bc9d653206f46b52b02cd6e5c83131f/src/meltano/core/block/parser.py#L309

Am thinking this tap needs a zhuzh?  It seems to be upsetting meltano.
